In [2]:
import torchvision.datasets as datasets
import numpy as np
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from pathlib import Path

In [6]:
from sklearn.decomposition import PCA
import numpy as np
import pathlib

def prep_mnist(mnist_set, n_components, pca=None):
    filtered_mnist_set = []
    for image in mnist_set:
        if image[1] == 0 or image[1] == 1:
            filtered_mnist_set.append(image)

    X = [np.asarray(val[0]).flatten() for val in filtered_mnist_set]
    Y = [val[1] for val in filtered_mnist_set]
    
    if not pca:
        pca = PCA(n_components=n_components)
        X_PC = pca.fit_transform(X)
    else:
        X_PC = pca.transform(X)
    return (X_PC, Y, pca)

In [9]:
mnist_trainset = datasets.MNIST(root='./data', train=True, download=True, transform=None)
mnist_testset = datasets.MNIST(root='./data', train=False, download=True, transform=None)

X_PC, Y, pca = prep_mnist(mnist_trainset, 2)
X_test_PC, Y_test, _ = prep_mnist(mnist_testset, 2, pca)

In [54]:
X=X_PC
Y=Y
X0 = np.array([X[i] for i in range(len(X)) if Y[i] == 0])
X1 = np.array([X[i] for i in range(len(X)) if Y[i] == 1])
mean0 = np.mean(X0, axis=0)
mean1 = np.mean(X1, axis=0)
covariance0 = np.cov(X0, rowvar=False)
covariance1 = np.cov(X1, rowvar=False)

In [57]:
covariance0

array([[215286.02496941, -23351.21030259],
       [-23351.21030259, 190498.53992741]])

In [44]:
(X0 - mean0) (X0 - mean0).T

TypeError: 'numpy.ndarray' object is not callable

In [ ]:
acum = 0
for i in X0.shape[0]:
    acum += (X0[0] - mean0) * (X0[0] - mean0).T

In [46]:
(X0[0] - mean0) * (X0[0] - mean0).T

array([ 9154.75288782, 92587.5551902 ])

In [41]:
foo.shape

(2, 5923)

In [42]:
(X0 - mean0).shape

(5923, 2)

In [45]:
X0[0]

array([1119.66338805,  321.49815688])